# Generated by Django 4.0.4 on 2022-05-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_category_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
